version: "3.8"

services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/universal:latest
    # Monta el workspace en el contenedor de desarrollo
    volumes:
      - ..:/workspaces/Data-Logistics-Analytics-Pipeline:cached
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: miusuario      
#      POSTGRES_DB: mibasedatos
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data: